name: clean_architecture
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Service locator
  get_it: ^3.1.0
  # BloC for state management
  flutter_bloc: ^3.2.0
  # Value equality
  equatable: ^1.1.0
  # Functional programming
  dartz: ^0.8.9
  http: ^0.12.0+4
  # Local cache
  shared_preferences: ^0.5.6+1
  # Web Viewer
  webview_flutter: ^0.3.18+1
  # Data Connection Checker
  data_connection_checker: ^0.3.4
  # JSON Serializer generator
  build_runner: ^1.7.4
  json_serializable: ^3.2.5
  meta: ^1.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^4.1.1
  pedantic: ^1.8.0

flutter:

  uses-material-design: true
  assets:
    - images/

